### ISSUE TITLE
Build docs / makefile?

### ISSUE THREAD

**Issue by greigs** [ValleyBell/MidiConverters#1]
I'm trying to figure out how to build these tools but it would be good to know the parameters for the gcc / g++ command or have a makefile available.

**Comment by ValleyBell** [comment]
There are no special parameters for GCC/G++ required, unless the readme has a "Compilation note" for it.

In general you can compile `tool.c` to an executable `tool` (or `tool.exe` on Windows) with this line:
```
gcc tool.c -o tool
```
There's really nothing else you need.

Maybe I may write a Makefile for them sometime in the future, but I can't make any promises.

**Comment by greigs** [comment]
Thanks for clarifying. Seems I have something strange with my gcc setup as I was getting errors like the one below, which prompted me to raise this issue. However g++ works just fine. So if in doubt use g++ I guess!

 ```
gcc ngp2mid.c -o ngp2mid
/tmp/ccTQdAJE.o: In function `DB2Mid':
ngp2mid.c:(.text+0xe3a): undefined reference to `pow'
```

**Comment by ValleyBell** [comment]
ohh, you're right.

GCC needs the math library linked for some functions. (done with `-lm`) I keep forgetting about that.  
I used Visual Studio to develop most of these tool and VS doesn't have the maths library separated from the rest. (I don't have VS project files, because I always just add them temporarily to a generic project.)

**Comment by greigs** [comment]
Good to know. Whenever I see projects with simple looking .h and .c files I tend to try gcc first in linux, or g++ if I see cpp. It works most of the time. Getting VS setup for anything other than .NET be tricky - lots of things to get wrong without project files.

**Comment by tcdw** [comment]
> Actually, you don't need the vgmtools repo. Instead you change the `-I` parameter to `-I.` and it works.

Ah, I didn't realize that. Thanks for pointing out!
