### ISSUE TITLE
Extract MIDI from Virtua On

### ISSUE THREAD

**Issue by 94math** [ValleyBell/MidiConverters#10]
Hello,

I'm fairly new to Midi extraction so i'm having a little bit of trouble. 
I generated the exe file with:
`gcc Soundfont.c M2MidiDec.c -o M2MidiDec`
But now, what file do i have to drag in to the .exe? The txt mentions, for Virtua on, 
Sound Program: v2 epr-18670.31, but i tried with it and nothing happened.

Thank you for your time!

**Comment by ValleyBell** [comment]
When you run the tool without parameters, it says:

```
Usage: M2MidiDec.exe [-options] mode sound_program.bin [samples1.bin] ... [samples4.bin]
Modes:
    mus - extract music to MIDI files
[...]
```

Thus, you need to extract `von.zip` and then run

```
M2MidiDec.exe mus epr-18670.31
```

**Comment by 94math** [comment]
Thank you!
