### ISSUE TITLE
tsd2mid fails to convert "VT_04_MD.M_"

### ISSUE THREAD

**Issue by soltune** [ValleyBell/MidiConverters#13]
`tsd2mid` fails to convert only "VT_04_MD.M_" of Brandish VT. (I have confirmed that all ED4 files can be converted correctly.)
I tried to give some options but no luck.
Are there any ideas I am missing?

Error messages are as follows
```
Falcom TotalSoundDriver -> Midi Converter
-----------------------------------------
Error Track 0: Unhandled command 0xE2 at position 0x544F!
Warning Track 1: Invalid channel mode 0x02X
Error Track 1: Unhandled command 0xE3 at position 0x6468!
Warning Track 3: Invalid channel mode 0x02X
Error Track 3: Unhandled command 0xE0 at position 0x0602!
Error Track 4: Unhandled command 0xB0 at position 0x0272!
Error Track 5: Unhandled command 0xB0 at position 0x10B8!
Error Track 6: Unhandled command 0xC2 at position 0x342A!
Error Track 7: Unhandled command 0xE2 at position 0x544F!
Error Track 8: Unhandled command 0xC3 at position 0x76E2!
Error Track 10: Unhandled command 0xE1 at position 0x2C2D!
Early EOF when trying to read track 12!
Done.
```

**Comment by ValleyBell** [comment]
I'm pretty sure that your file got corrupted.

For reference, the correct file begins with this byte sequence:
```
5000 5701 FD01 9003 7D04 9A05 BC06 9008
```

**Comment by soltune** [comment]
Hi  @ValleyBell 

Thanks for making me realize my dumb mistake!
As you said my file started with the string as 'MThd...'. (i.e. midi file)
The original file seemed to be overwritten, because 'output.mid' option was missing.
I was surely confirm that the conversion was successful with correct one!

Thanks again
