### ISSUE TITLE
Wolfteam X68000 games - extracting archives?

### ISSUE THREAD

**Issue by mistydemeo** [ValleyBell/MidiConverters#15]
For `wtmf2mid`, you mention that the X68000 Wolfteam games store their MIDI data in LZSS-compressed archives. Do you have a tool to extract those, or otherwise have any notes on the format I could draw on? Thank you!

**Comment by mistydemeo** [comment]
Great, thank you! I'll give that a go.

I'm also curious about the sysex for the MT-32 tracks in the Wolfteam games. I noticed it doesn't seem to be embedded in the PC-98 MIDIs I extracted. Did you find where it's stored, or just capture it from the games when they're running?

**Comment by ValleyBell** [comment]
SysEx data is stored in separate files as raw SysEx data dumps. (commonly known as `.syx` files.) They are loaded at boot time.

X68000 games usually have them with a `.SEN` extension. (e.g. `AO.SEN` or `SOL.SEN`).  
In PC-98 games their file name is usually not obvious. (Arcus 3: `00E_DA0E`, Niko2: `071_MI71`, Zan 2: `03F_MU0F`)

All SysEx dumps are easily identifyable though - they begin with `F0 41 10 16 12`.

Granada is the only exception: It has SysEx dumps in text form in `GRANADA.LA`.

**Comment by mistydemeo** [comment]
Thank you! Sorry for the late reply. I appreciate the help!
