### ISSUE TITLE
How to use M2MidiDec?

### ISSUE THREAD

**Issue by TailsHead** [ValleyBell/MidiConverters#18]
I'd love to extract the midis from Sonic The Fighters, but I have no idea how to use M2MidiDec. Help would be very appreciated!

**Comment by ValleyBell** [comment]
same as #10

**Comment by TailsHead** [comment]
I'm confused, when I paste "gcc Soundfont.c M2MidiDec.c -o M2MidiDec" into powershell, I get this error
![image_2024-05-11_113543880](https://github.com/ValleyBell/MidiConverters/assets/92544778/e9df120f-dc8d-4205-89f9-25dec3197171)

**Comment by TailsHead** [comment]
I can't figure out how to get the .exe

**Comment by ValleyBell** [comment]
eww.... what GCC version is this and how did you install it?
For whatever reason "turn warnings into errors" is active.

Can you add `-Wno-incompatible-pointer-types` to the command line when compiling?

**Comment by TailsHead** [comment]
interesting.. i added ur command and it compiled just fine. i installed GCC version 14.1.0 through MINGW64 with this code `pacman -S mingw-w64-x86_64-gcc`
