### ISSUE TITLE
ngp2mid - Failure to convert (sonic)

### ISSUE THREAD

**Issue by greigs** [ValleyBell/MidiConverters#2]
Using ngp2mid gives me errors when using it with the sonic pocket rom found on archive.org.
I have confirmed that the following is set correctly for this rom:
`static UINT8 DrvVer = DRV_VER_09F5;`

```
g++ ngp2mid.c -o ngp2mid
./ngp2mid Sonic_the_Hedgehog_Pocket_Adventure_1999_Sega.bin sonicmidi.mid

Converting Sonic_the_Hedgehog_Pocket_Adventure_1999_Sega.bin ...
Track 0 (Channel 1) ...
Track 1 (Channel 1) ...
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

If I use the -fno-stack-protector flag...
```
g++ -fno-stack-protector ngp2mid.c -o ngp2mid
./ngp2mid Sonic_the_Hedgehog_Pocket_Adventure_1999_Sega.bin sonicmidi.mid

Converting Sonic_the_Hedgehog_Pocket_Adventure_1999_Sega.bin ...
Track 0 (Channel 1) ...
Segmentation fault (core dumped)
```

**Comment by greigs** [comment]
Looking into this further I found the discussion at [https://forums.sonicretro.org/index.php?showtopic=36354&st=15](https://forums.sonicretro.org/index.php?showtopic=36354&st=15). It seems I might need the files for each track extracted from the rom at their specific offsets.

**Comment by greigs** [comment]
Found what I was looking for. For anyone having the same issue, it does require the songs to be extracted from the rom first. For this game I was able to find everything I needed here: [https://forums.sonicretro.org/index.php?showtopic=36156](https://forums.sonicretro.org/index.php?showtopic=36156)

**Comment by ValleyBell** [comment]
Yes, I'm afraid you need the raw, extracted sequences.

Right now, it's probably easiest to just grab the [source of my Sonic Pocket Winter hack](http://vgmrips.net/misc/SPW_full_source.7z). It has all the files pre-extracted, but it also includes tools for extracting sequences from a vanilla SPA ROM.  
`Tools/Anls_Sound.cpp` is the sound analysis program for SPA. (The sound list offset is hardcoded right now, so it only works with the "final" SPA ROM.)
