### ISSUE TITLE
Add support for DiamondWare DWM

### ISSUE THREAD

**Issue by Sembiance** [ValleyBell/MidiConverters#20]
As far as I can tell, the DiamondWare DWM format that is very close to MIDI.

Sample files here: https://sembiance.com/fileFormatSamples/music/diamondWareDigitizedMusic/

This project talks a bit about the DWM files and how it relates to MIDI: https://github.com/Moufinure/quiver_ripper
This DOS software can convert MIDI to DWM: https://archive.org/details/DiamondWaresSoundToolKit_1020

Not sure how hard it would be to convert back to MIDI, but it would be awesome if such a converter were to exist.

**Comment by ValleyBell** [comment]
One of the linked pages says:
> .DWM which is MIDI converted into a custom format which seems to make use of OPL commands;

"make use of OPL commands" is more a hint that the format is close to VGM/DRO/IMF than it is to MIDI. (That the source material is a MIDI file doesn't matter: You could record a MIDI to WAV/MP3 as well and the difference between those formats couldn't be larger.)

Looking at the example files, they don't seem to resemble MIDI structures at all, so it is probably something different.

I won't completely rule out the chance of writing a converter, but doing so would definitely require a fair bit of reverse-engineering of the DWM format.

**Comment by Sembiance** [comment]
Ahh, it does indeed sound more complicated than just reversing back to MIDI. I'd say go ahead and close this issue as 'Not Planned' due to it not being as MIDI-like as I thought it may have been when I first submitted the issue.
