### ISSUE TITLE
M2MidiDec - Unsuported sound driver version on Sonic the Fighters for SF2 extract

### ISSUE THREAD

**Issue by tlsctf2** [ValleyBell/MidiConverters#23]
hello hello, I'm not all that familiar with how code stuff works so please bear with me

I've gotten M2MidiDec compiled with help from other issues opened here, but when I try to extract the soundfont from a rom of Sonic the Fighters or Sonic Championship, I get an "unsupported sound driver version" error, and nothing happens. normally I would write it off as me just having the wrong version like the error said, but since a disassembly of STF's sound driver is specifically cited as what the code was written around, I wanted to ask if there might be something else I'm missing or doing wrong here

the program is able to extract the midi files just fine, and the wav extract also seems to work as expected, but specifically the sf2 one isn't playing nice with me for some reason

**Comment by tlsctf2** [comment]
edited to clarify I'm talking about M2MidiDec, mb

**Comment by ValleyBell** [comment]
It doesn't make sense that MIDI and WAV extraction works and SF2 extraction throws an "Unsupported sound driver" error.

How are you calling the tool for WAV and SF2 extraction? (exact command line with all parameters, please)

**Comment by tlsctf2** [comment]
for wav:
`m2mididec.exe wav epr-19021.31 mpr-19022.32 mpr-19023.33 mpr-19024.34 mpr-19025.35`
for sf2:
`m2mididec.exe sf2 mpr-19022.32 mpr-19023.33 mpr-19024.34 mpr-19025.35`

however, in running back through this just now after getting more sleep (I had been very tired when I opened this issue), I used this for sf2 instead and got it working:
`m2mididec.exe sf2 epr-19021.31 mpr-19022.32 mpr-19023.33 mpr-19024.34 mpr-19025.35`
not sure why I never tried that initially in hindsight, must have been the lack of sleep making me not realize that's maybe a little important. the exact wording of the error threw me off; I would have expected something like what I get when I try to extract to wav without the samples chunk ("Sample ROMs are required for sample dumping!") instead of saying the whole driver is wrong, but I may just be uninformed about that

at any rate, I did get the sf2 just now, have yet to test it out but it's further than I got before lol

**Comment by ValleyBell** [comment]
Okay, you initially forgot to specify the sound program ROM (the `epr` file). That's actually what I assumed could have happened. (which is why I was asking for the command line used)

You *always* have to specify the program ROM, because that is where all the tables are stored in. The sample ROMs (`mpr` files) contain only the raw sample data with no indication about where a certain sample begins, loops and ends. That information is stored in the `epr` program ROM, which is why it is a requirement in any case.

The tool is explicit about this on its help screen:
> Usage: M2MidiDec.exe [-options] mode sound\_program.bin [samples1.bin] ... [samples4.bin]
