### ISSUE TITLE
Feature Request: M2MidiDec Sample Extraction Labels?

### ISSUE THREAD

**Issue by cglmrfreeman** [ValleyBell/MidiConverters#9]
Greetings,

I'm not 100% familiar yet with how audio is called in the Model2 games, but as I understand it a "sound code" relates to the sample? For example the first playable sound in the sound test of the game is named "sd_jump_1" with a sound code of "0xAE1100" and your program names this file "Ins50_d00_Smpl90".

A list of sound codes followed by names can be found within the game's program data starting at offset 0x9A12C.

Perhaps there could be some way to properly label non-instrumental sound files by referencing the data in the program roms?

**Comment by ValleyBell** [comment]
`AE1100` probably means "play sound effect" (`AE`) number 17 (`11h`).
I'm not completely sure how playing SFX works as I haven't looked at the game's ASM code for a long time, but based on how the music works, it goes like this:

- main CPU: play SFX with ID 11h
- sound CPU: load SFX 11h
- on channel C, load instrument I
- play note N (of instrument I), which plays sample S

I'm afraid assigning names is a bit difficult with all those sample remapping.  
Also, the tool relies on only the sound ROMs and I'd like to not require program ROMs as well.

**Comment by cglmrfreeman** [comment]
Alright, fair enough.

**Comment by ValleyBell** [comment]
I had a deeper look at the inner workings othe sound driver and have a small correction:

`AE1bnn` = "play sequence nn in bank b" (see also [the full sound code list I posted on Sonic Retro](https://forums.sonicretro.org/index.php?threads/sonic-the-fighters-disassembly-and-discoveries-from-it.39390/#post-968974))

- main CPU: play sequence 0 in bank 1
- sound CPU: load sequence - it's a sound effect
- execute MIDI command `9C004B` -> channel 12, note 0, velocity 75
- play note 0 of instrument 80 (0x50) (which the sound driver loads on this channel on boot) -> play sample 0x090

This doesn't make it better, but I guess it's good to know how it really works.
